### ISSUE TITLE
The lack of package

### ISSUE THREAD

**Issue by meission** [cloudflare/tls-tris#12]
I do build  
cipher_suites.go:9:2: cannot find package "crypto/chacha20poly1305" in any of:
	/usr/local/go/src/crypto/chacha20poly1305 (from $GOROOT)
~/gopath/src/crypto/chacha20poly1305 (from $GOPATH)

**Comment by meission** [comment]
the "crypto/chacha20poly1305" is not in  https://github.com/golang/go/tree/master/src/crypto

**Comment by FiloSottile** [comment]
As mentioned in the description, this package is experimental and comes with no guarantee of being secure or functional, or support of any kind.

That said, the error you see is because you can't build it with normal Go, you have to use `_dev/go.sh`.
