### ISSUE TITLE
document what the Committer is supposed to do (or remove it)

### ISSUE THREAD

**Issue by marten-seemann** [cloudflare/tls-tris#131]
`Committer` is an interface that the `Conn` is type asserted against in https://github.com/cloudflare/tls-tris/blob/e20b4d2a9a269651cbd39fd66a40caa56d4c4130/13.go#L155-L159
There's no explanation what the purpose of this is, and also the definition of the interface in https://github.com/cloudflare/tls-tris/blob/e20b4d2a9a269651cbd39fd66a40caa56d4c4130/handshake_server.go#L19-L21 doesn't provide any clues.

Since this is a public interface tris exposes, it should either be properly documented, or removed.

**Comment by Lekensteyn** [comment]
It was added in ea17b0c2255db074941b16938f654029b12abd46 and moved in 0d97989e0d689bd976ede383b4db99feb5d9fe1f. My guess is that this mechanism would allow server to control whether a (replayed) 0-RTT handshake is okay or not.

For the lack of an actual implementation, it is probably fine to remove it.

**Comment by henrydcase** [comment]
This code doesn't seem to be useful for anything.
