### ISSUE TITLE
build: Create debian package during build

### ISSUE THREAD

**Issue by henrydcase** [cloudflare/tls-tris#174]
Goal is to create go package with this implementation of TLS

**Comment by Lekensteyn** [comment]
What kind of installation prefix would you like to use? Instead of providing a deb package, a tarball could also be created, similar to https://golang.org/doc/install.

It should be pretty straight-forward though, just copy _dev/GOROOT/... What is the intended use?

**Comment by henrydcase** [comment]
I would like something very similar to our internal build of go-crypto, hence .deb

**Comment by henrydcase** [comment]
I mean, tar.gz could *also* be provided and that's beneficial.
