### ISSUE TITLE
Add nginx TLSv1.3 Patch in "_dev"

### ISSUE THREAD

**Issue by Henrocker** [cloudflare/tls-tris#20]
Since caddy owns its tls-patch already in this repository, it would be nice to have one for nginx, too, because currently nginx does not support the TLSv1.3 command out of the box and I know there are Dockerpatches for nginx but none for standalone or compiled from source nginx.

**Comment by FiloSottile** [comment]
This repository is specifically about a Go implementation of TLS 1.3, so it is not applicable to NGINX.
