### ISSUE TITLE
Client authentication in TLS 1.3

### ISSUE THREAD

**Issue by Lekensteyn** [cloudflare/tls-tris#41]
To support client authentication, the server must be extended to send a CertificateRequest message and verify the response (Certificate, CertificateVerify).

The client must be adjusted to process a CertificateRequest message.

Note that post-handshake authentication is out-of-scope for this issue.
Note: draft 19 changes the CertificateRequest format.

Draft -18:
```
      opaque DistinguishedName<1..2^16-1>;

      struct {
          opaque certificate_extension_oid<1..2^8-1>;
          opaque certificate_extension_values<0..2^16-1>;
      } CertificateExtension;

      struct {
          opaque certificate_request_context<0..2^8-1>;
          SignatureScheme
            supported_signature_algorithms<2..2^16-2>;
          DistinguishedName certificate_authorities<0..2^16-1>;
          CertificateExtension certificate_extensions<0..2^16-1>;
      } CertificateRequest;
```

Draft -19 to -22:
```
      struct {
          opaque certificate_request_context<0..2^8-1>;
          Extension extensions<2..2^16-1>;
      } CertificateRequest;
```
(`certificate_authorities` got moved to a separate extension, `signature_algorithms` is a required extension.)

STATUS
Branch https://github.com/cloudflare/tls-tris/commits/pwu/client-auth implements the new CertificateRequest format and wires it up for the client. TODO:
 - implement server side (likely: (1) refactor (extract) TLS 1.2 certificate validation logic (2) wire up TLS 1.3 with this logic)
 - Enable client cert tests in the config.json file, based on https://github.com/FiloSottile/crypto-tls-bogo-shim/pull/2
 - Test and fix bugs.

**Comment by henrydcase** [comment]
Any update here? It seems "Enable client cert tests" point has been done already, isn't?

**Comment by Lekensteyn** [comment]
bogo shim has been updated with a config that ignores client cert tests, but the actual client cert auth has still not been implemented yet (see for example the TODO in 13.go)
