### ISSUE TITLE
Offer helpful error message for RSA keys too short

### ISSUE THREAD

**Issue by FiloSottile** [cloudflare/tls-tris#60]
If an RSA key is too short for PSS, the handshake fails with an unhelpful `crypto/rsa: encoding error`.

Pick a minimum bitlen (or find it in the spec) and return a helpful error message.

**Comment by henrydcase** [comment]
Is it really TLS tris problem? Shouldn't it be fixed in crypto?

**Comment by FiloSottile** [comment]
You have a point! https://github.com/golang/go/issues/23736
