### ISSUE TITLE
TLS-13-Draft-23 plan?

### ISSUE THREAD

**Issue by phuslu** [cloudflare/tls-tris#73]
Since draft-23 support is rolled out by chrome 65, Is there any plan for tls-tris draft-23 plan?

Thanks!

**Comment by phuslu** [comment]
In my understanding, to upgrade draft-22 to draft-23 needs,

- [ ] change `extensionKeyShare` from 40 to 51
- [ ] implement `extensionDummyPQPadding`

Am I right? Thanks!

**Comment by henrydcase** [comment]
@phuslu Yes, there is a plan to upgrade but probably straight to draft-26 in order to be as close to final release as possible

**Comment by henrydcase** [comment]
I don't think we will implement ``extensionSignatureAlgorithmsCert``. It seems x509 is missing support for that - also at the moment it's not that important
