### ISSUE TITLE
Enable TLS 1.3 by default

### ISSUE THREAD

**Issue by henrydcase** [cloudflare/tls-tris#75]
Currently TLS 1.2 is used by default. Internally we need to have TLS 1.3 - we will set default version to the TLS 1.3 draft 22

**Comment by Lekensteyn** [comment]
draft 28 has been approved by the IESG, perhaps it is better to implement that before flipping the switch?

**Comment by henrydcase** [comment]
I need this internally, but probably I can do it on separated branch.
